[[d1_databases]]
binding = "DB" # Should match preview_database_id
database_name = "edge-leaderboard-db"
database_id = "142cc588-5ee5-48cc-8e6e-07eb7edb8b4c" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "DB" # Required for Pages local development